SELECT [idmovimento]
      ,[idcenario]
      ,[idpessoaempresa]
      ,[idindexadoreconomicofinanceiro]
      ,[idlote]
      ,[idpessoaclientefornecedor]
      ,[indfinalizado]
      ,[tipomovimento]
      ,[numeromovimento]
      ,[numerodocumentoinicial]
      ,[numerodocumentofinal]
      ,[dataemissao]
      ,[datamovimento]
      ,[valormovimento]
      ,[valorfrete]
      ,[valorseguro]
      ,[valordespesa]
      ,[valordespesaalimentacao]
      ,[valordespesavaletransporte]
      ,[valordesconto]
      ,[valormulta]
      ,[valorjuros]
      ,[idowner]
      ,[indgeradosistemaexterno]
      ,[idsistemaorigem]
      ,[valorst]
      ,[valorvendor]
      ,[valorliquido]
      ,[idnaturezaoperacaorps]
      ,[idusuariolog]
      ,[datahoralog]
      ,[idcondicaopagamento]
      ,[dataentradacontingencia]
      ,[justificativacontingencia]
      ,[valorabatimentonaotributado]
      ,[valorabatimentopiscofinszfm]
      ,[idorigemregistro]
      ,[iddadosinscricaoestadualempresa]
      ,[iddadosinscricaoestadualclientefornecedor]
      ,[datalancamentoextemporaneo]
      ,[dataemissaofinal]
      ,[valordeducao]
      ,[valoroutrasretencoes]
  FROM [NG_ADM].[dbo].[adm_movimento]
  where numeromovimento='0000159561'
GO


select * 
FROM [NG_ADM].[dbo].[adm_movimento]
where numerodocumentoinicial like '%2385%'

UPDATE [NG_ADM].[dbo].[adm_movimento]
SET numerodocumentoinicial='000644'
where numeromovimento='0000154827'